from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from crxzipple.modules.settings.application.bootstrap import BootstrapSettingsResource
from crxzipple.shared.settings import SettingsResourceRef


def access_config_resources(settings: object) -> tuple[BootstrapSettingsResource, ...]:
    del settings
    return (
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="openai-api-key",
            display_name="OpenAI API Key",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "openai-api-key",
                "binding_kind": "api_key",
                "source_kind": "env",
                "source_ref": "OPENAI_API_KEY",
                "masked_preview": "env:OPENAI_API_KEY",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {"settings_owner": "access_config"},
                "enabled": True,
            },
            source="bootstrap:access",
        ),
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="codex-oauth-default",
            display_name="Codex OAuth Account",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "codex-oauth-default",
                "binding_kind": "oauth2_account",
                "source_kind": "oauth_account",
                "source_ref": "openai-codex:default",
                "masked_preview": "oauth_account",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {
                    "settings_owner": "access_config",
                    "provider_id": "openai-codex",
                },
                "enabled": True,
            },
            source="bootstrap:access",
        ),
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="brave-search-api-key",
            display_name="Brave Search API Key",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "brave-search-api-key",
                "binding_kind": "api_key",
                "source_kind": "env",
                "source_ref": "BRAVE_SEARCH_API_KEY",
                "masked_preview": "env:BRAVE_SEARCH_API_KEY",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {"settings_owner": "access_config"},
                "enabled": True,
            },
            source="bootstrap:access",
        ),
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="itick-api-token",
            display_name="iTick API Token",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "itick-api-token",
                "binding_kind": "api_key",
                "source_kind": "env",
                "source_ref": "ITICK_API_TOKEN",
                "masked_preview": "env:ITICK_API_TOKEN",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {"settings_owner": "access_config"},
                "enabled": True,
            },
            source="bootstrap:access",
        ),
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="access-binding:lark-app-id",
            display_name="Lark App ID",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "access-binding:lark-app-id",
                "binding_kind": "api_key",
                "source_kind": "env",
                "source_ref": "LARK_APP_ID",
                "masked_preview": "env:LARK_APP_ID",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {"settings_owner": "access_config"},
                "enabled": True,
            },
            source="bootstrap:access",
        ),
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="access-binding:lark-app-secret",
            display_name="Lark App Secret",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "access-binding:lark-app-secret",
                "binding_kind": "app_secret",
                "source_kind": "env",
                "source_ref": "LARK_APP_SECRET",
                "masked_preview": "env:LARK_APP_SECRET",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {"settings_owner": "access_config"},
                "enabled": True,
            },
            source="bootstrap:access",
        ),
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="access-binding:lark-verification-token",
            display_name="Lark Verification Token",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "access-binding:lark-verification-token",
                "binding_kind": "webhook_secret",
                "source_kind": "env",
                "source_ref": "LARK_VERIFICATION_TOKEN",
                "masked_preview": "env:LARK_VERIFICATION_TOKEN",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {"settings_owner": "access_config"},
                "enabled": True,
            },
            source="bootstrap:access",
        ),
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="access-binding:lark-encrypt-key",
            display_name="Lark Encrypt Key",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "access-binding:lark-encrypt-key",
                "binding_kind": "webhook_secret",
                "source_kind": "env",
                "source_ref": "LARK_ENCRYPT_KEY",
                "masked_preview": "env:LARK_ENCRYPT_KEY",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {"settings_owner": "access_config"},
                "enabled": True,
            },
            source="bootstrap:access",
        ),
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="access-binding:lark-bot-open-id",
            display_name="Lark Bot Open ID",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "access-binding:lark-bot-open-id",
                "binding_kind": "api_key",
                "source_kind": "env",
                "source_ref": "LARK_BOT_OPEN_ID",
                "masked_preview": "env:LARK_BOT_OPEN_ID",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {"settings_owner": "access_config"},
                "enabled": True,
            },
            source="bootstrap:access",
        ),
        _resource(
            kind="access-assets",
            owner="access",
            resource_id="access-binding:webhook-secret",
            display_name="Webhook Secret",
            payload={
                "access_declaration_kind": "credential_binding",
                "binding_id": "access-binding:webhook-secret",
                "binding_kind": "webhook_secret",
                "source_kind": "env",
                "source_ref": "WEBHOOK_SECRET",
                "masked_preview": "env:WEBHOOK_SECRET",
                "status": "active",
                "redaction_policy": {"mode": "metadata_only"},
                "metadata": {"settings_owner": "access_config"},
                "enabled": True,
            },
            source="bootstrap:access",
        ),
    )


def _resource(
    *,
    kind: str,
    owner: str,
    resource_id: str,
    display_name: str,
    payload: Mapping[str, Any],
    source: str,
) -> BootstrapSettingsResource:
    return BootstrapSettingsResource(
        ref=SettingsResourceRef(
            resource_id=resource_id,
            resource_kind=kind,
            owner_module=owner,
            display_name=display_name,
        ),
        payload=dict(payload),
        source=source,
        metadata={"bootstrap_source": source},
    )
