"""Browser-side JavaScript expression export surface for the action engine."""

from __future__ import annotations

from .action_engine_bulk_selection_scripts import (
    _BULK_SELECTION_DESCENDANTS_EXPRESSION,
    _BULK_SELECTION_EXPRESSION,
)
from .action_engine_overlay_scripts import (
    _ACTIVE_OVERLAY_SELECTOR_EXPRESSION,
    _ASSOCIATED_OVERLAY_SELECTOR_EXPRESSION,
    _AUTOCOMPLETE_OVERLAY_STATUS_EXPRESSION,
    _DATEPICKER_DAY_ORDINAL_EXPRESSION,
    _DATEPICKER_PANEL_STATUS_EXPRESSION,
)
from .action_engine_script_markers import (
    _INTERACTIVE_SNAPSHOT_MARKER,
    _ACTIVE_OVERLAY_MARKER,
    _ASSOCIATED_OVERLAY_MARKER,
    _AUTOCOMPLETE_OVERLAY_STATUS_MARKER,
    _DATEPICKER_PANEL_STATUS_MARKER,
    _DATEPICKER_DAY_ORDINAL_MARKER,
    _TARGET_INFO_MARKER,
    _BULK_SELECTION_MARKER,
    _TEXT_MATCH_ORDINAL_MARKER,
    _TEXT_MATCH_DETAILS_MARKER,
)
from .action_engine_snapshot_scripts import _INTERACTIVE_SNAPSHOT_EXPRESSION
from .action_engine_target_text_scripts import (
    _BROWSER_SCROLL_INTO_VIEW_EXPRESSION,
    _TARGET_INFO_EXPRESSION,
    _TEXT_MATCH_DETAILS_EXPRESSION,
    _TEXT_MATCH_ORDINAL_EXPRESSION,
)

__all__ = (
    "_INTERACTIVE_SNAPSHOT_MARKER",
    "_ACTIVE_OVERLAY_MARKER",
    "_ASSOCIATED_OVERLAY_MARKER",
    "_AUTOCOMPLETE_OVERLAY_STATUS_MARKER",
    "_DATEPICKER_PANEL_STATUS_MARKER",
    "_DATEPICKER_DAY_ORDINAL_MARKER",
    "_TARGET_INFO_MARKER",
    "_BULK_SELECTION_MARKER",
    "_TEXT_MATCH_ORDINAL_MARKER",
    "_TEXT_MATCH_DETAILS_MARKER",
    "_INTERACTIVE_SNAPSHOT_EXPRESSION",
    "_BULK_SELECTION_EXPRESSION",
    "_BULK_SELECTION_DESCENDANTS_EXPRESSION",
    "_ACTIVE_OVERLAY_SELECTOR_EXPRESSION",
    "_ASSOCIATED_OVERLAY_SELECTOR_EXPRESSION",
    "_AUTOCOMPLETE_OVERLAY_STATUS_EXPRESSION",
    "_DATEPICKER_PANEL_STATUS_EXPRESSION",
    "_DATEPICKER_DAY_ORDINAL_EXPRESSION",
    "_TARGET_INFO_EXPRESSION",
    "_BROWSER_SCROLL_INTO_VIEW_EXPRESSION",
    "_TEXT_MATCH_ORDINAL_EXPRESSION",
    "_TEXT_MATCH_DETAILS_EXPRESSION",
)
