from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol


class OperationsToolQueryPort(Protocol):
    @property
    def concurrency_policy(self) -> Any: ...

    def list_tools(self) -> tuple[Any, ...]: ...

    def list_enabled_tools(self) -> tuple[Any, ...]: ...

    def list_tool_runs(self, *, limit: int | None = None) -> tuple[Any, ...]: ...

    def list_tool_workers(self) -> tuple[Any, ...]: ...

    def list_tool_run_assignments(self) -> tuple[Any, ...]: ...

    def check_readiness(self, tool_id: str) -> dict[str, Any] | None: ...

    def check_access_readiness(self, tool_id: str) -> Any | None: ...

    def list_sources(self) -> tuple[Any, ...]: ...

    def list_functions(self) -> tuple[Any, ...]: ...

    def list_provider_backends(self) -> tuple[Any, ...]: ...

    def check_provider_backend_readiness(self, backend: Any) -> Any | None: ...

    def list_source_discovery_runs(
        self,
        source_id: str,
        *,
        limit: int = 20,
    ) -> tuple[Any, ...]: ...


class OperationsArtifactReadPort(Protocol):
    def get_artifact(self, artifact_id: str) -> Any: ...


class OperationsRemoteToolRuntimeRegistryPort(Protocol):
    def snapshot(self) -> Mapping[str, Any]: ...

    def registrations(self) -> tuple[Any, ...]: ...
