from __future__ import annotations

ORCHESTRATION_INGRESS_DISPATCH_OWNER_KIND = "orchestration_ingress"
ORCHESTRATION_STEP_DISPATCH_OWNER_KIND = "orchestration_step"
ORCHESTRATION_TURN_MAINTENANCE_DISPATCH_OWNER_KIND = (
    "orchestration_turn_maintenance"
)
ORCHESTRATION_CONTINUATION_DISPATCH_OWNER_KIND = "orchestration_continuation"

ORCHESTRATION_DISPATCH_OWNER_KINDS: frozenset[str] = frozenset(
    {
        ORCHESTRATION_CONTINUATION_DISPATCH_OWNER_KIND,
        ORCHESTRATION_INGRESS_DISPATCH_OWNER_KIND,
        ORCHESTRATION_STEP_DISPATCH_OWNER_KIND,
        ORCHESTRATION_TURN_MAINTENANCE_DISPATCH_OWNER_KIND,
    },
)


__all__ = [
    "ORCHESTRATION_CONTINUATION_DISPATCH_OWNER_KIND",
    "ORCHESTRATION_DISPATCH_OWNER_KINDS",
    "ORCHESTRATION_INGRESS_DISPATCH_OWNER_KIND",
    "ORCHESTRATION_STEP_DISPATCH_OWNER_KIND",
    "ORCHESTRATION_TURN_MAINTENANCE_DISPATCH_OWNER_KIND",
]
