#!/usr/bin/env bash
set -euo pipefail

if [[ -n "${BASH_VERSION:-}" ]]; then
  SCRIPT_PATH="${BASH_SOURCE[0]}"
elif [[ -n "${ZSH_VERSION:-}" ]]; then
  SCRIPT_PATH="${(%):-%x}"
else
  SCRIPT_PATH="$0"
fi

ROOT_DIR="$(cd "$(dirname "${SCRIPT_PATH}")/../.." && pwd)"

source "${ROOT_DIR}/scripts/dev/redis-env.sh" >/dev/null

export CRXZIPPLE_POSTGRES_HOST="${CRXZIPPLE_POSTGRES_HOST:-127.0.0.1}"
export CRXZIPPLE_POSTGRES_PORT="${CRXZIPPLE_POSTGRES_PORT:-5432}"
export CRXZIPPLE_POSTGRES_DB="${CRXZIPPLE_POSTGRES_DB:-crxzipple}"
export CRXZIPPLE_POSTGRES_USER="${CRXZIPPLE_POSTGRES_USER:-crxzipple}"
export CRXZIPPLE_POSTGRES_PASSWORD="${CRXZIPPLE_POSTGRES_PASSWORD:-crxzipple}"

export APP_DATABASE_URL="${APP_DATABASE_URL:-postgresql+psycopg://${CRXZIPPLE_POSTGRES_USER}:${CRXZIPPLE_POSTGRES_PASSWORD}@${CRXZIPPLE_POSTGRES_HOST}:${CRXZIPPLE_POSTGRES_PORT}/${CRXZIPPLE_POSTGRES_DB}}"
APP_DATABASE_URL_DISPLAY="postgresql+psycopg://${CRXZIPPLE_POSTGRES_USER}:<redacted>@${CRXZIPPLE_POSTGRES_HOST}:${CRXZIPPLE_POSTGRES_PORT}/${CRXZIPPLE_POSTGRES_DB}"

cat <<EOF
Dev infra env loaded:
  CRXZIPPLE_PYTHON=$CRXZIPPLE_PYTHON
  PYTHONPATH=$PYTHONPATH
  APP_DATABASE_URL=$APP_DATABASE_URL_DISPLAY
  APP_EVENTS_BACKEND=$APP_EVENTS_BACKEND
  APP_EVENTS_REDIS_URL=$APP_EVENTS_REDIS_URL
EOF
